import Head from "next/head";
import styles from "@/styles/Home.module.css";



export default function Home() {
  return (
    <>
      <Head>
        <title>Best ERP Solutions</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} `}
      >
        <main>
          <h1 className="text-red">hello</h1>
        </main>
       
      </div>
    </>
  );
}
