import Head from "next/head";
import Hero from "../components/hero";
import "@/styles/globals.css";
import OurServices from "@/components/ourServices";
import WhyChooseUs from "@/components/whyChooseUs";

export default function Home() {
  return (
    <>
      <Head>
        <title>Best ERP Solutions</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main>
          <Hero />
          <OurServices />
          <WhyChooseUs />
        </main>
      </div>
    </>
  );
}
