import Head from "next/head";
import "@/styles/globals.css";
import HomePage from "@/components/home";

export default function Home() {
  return (
    <>
      <Head>
        <title>Best ERP Solutions</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main>
          <HomePage />
        </main>
      </div>
    </>
  );
}
